# Generated by Django 3.0.3 on 2020-04-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cases', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('recoveries', models.IntegerField(default=0)),
                ('date', models.DateField()),
            ],
        ),
    ]
